env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash

install: true

script:

- ./mvnw
- ./mvnw clean spotbugs:help
- ./mvnw clean spotbugs:spotbugs
- ./mvnw clean spotbugs:check

- ./gradlew
- ./gradlew clean spotbugsMain
- ./gradlew clean spotbugsTest
- ./gradlew clean check

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
