env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash

install: true

script:
- ./mvnw spotbugs:help
- ./mvnw spotbugs:check
- ./mvnw spotbugs:gui
- ./mvnw spotbugs:spotbugs
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
