env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash

install: true

script:

- ./mvnw
- ./mvnw clean package spotbugs:spotbugs -Ddetail=true

- ./gradlew
- ./gradlew clean check build

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
